### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by php5developer** [hippasus/ExchangeRates#1]
Hey,
When I make request to this URL
http://rate-exchange.appspot.com/currency?from=BHD&to=CLP
Server response 500 Internal Error.

**Comment by Wikunia** [comment]
At first: 
Thanks for this tool.
Here as well:
http://rate-exchange.appspot.com/currency?from=EUR&to=VND

And this two:
http://rate-exchange.appspot.com/currency?from=EUR&to=LAK & // Laos
http://rate-exchange.appspot.com/currency?from=EUR&to=KHR // Kambodia 
have an error :/

A fix would be really nice! ;)

**Comment by hippasus** [comment]
bug fixed for `EUR` to `VND` due to google add a space as thousand separator in the rate(https://www.google.com/ig/calculator?hl=en&q=1EUR=?VND).
Please note that `LAK` is not supported by google yet, hence, the new result for `EUR` to `LAK` will be `{"err": "not supported rate conversion."}`

**Comment by Wikunia** [comment]
Thanks for that ;)
That's bad that Google doesn't support this.
