### ISSUE TITLE
Not proper JSON format. Cannot be parsed as JSON.

### ISSUE THREAD

**Issue by lophesuicire** [hippasus/ExchangeRates#11]
Hello, I have stumbled upon your app and it is awesome. I noticed a small problem it cannot be properly parsed as JSON because the output is not proper. The value of the string "rate" is not within "" so any parser would crash trying to parse it.

Please tell me if you ever fix this so I could also change my code to properly parse it instead of cutting corners :). Thanks for the awesome app.
- Lophie

**Comment by hippasus** [comment]
Do u mean that `{"to": "EUR", "rate": 0.73959026699999997, "from": "USD"}` should be `{"to": "EUR", "rate": "0.73959026699999997", "from": "USD"}`?
Note that the rate here is a number, not string.

**Comment by lophesuicire** [comment]
Yes I am sorry I have been reading online and that format is actually
correct. However the problem I faced is failing to parse the json using the
class org.json.JSONObject on android sdk. Probably their fault or mine.
Your format is correct to stqndards. Sorry for wasting your time and thanks
for the reply.
