### ISSUE TITLE
Currency API down due to Google rate API doesn't exist any more.

### ISSUE THREAD

**Issue by hippasus** [hippasus/ExchangeRates#12]
The api http://www.google.com/ig/calculator?hl=en&q=1USD=?EUR is down in google side due to iGoogle down. We need to find a replacement here.

**Comment by Bearcosta** [comment]
Any progress on this? 

Cheers

**Comment by hippasus** [comment]
I've deployed a new version, it should work before 2013-11-09 9:00AM UTC.

**Comment by Bearcosta** [comment]
Wicked, cheers man!

**Comment by surajravi** [comment]
You may not know me but I just started following your project.

I myself was trying to fix your code to work by employing the yahoo API.

But I guess you beat me to it.

Thanks a ton!

You will have my donation as soon as I get my next pay( sorry it won't be much as I am grad student working min wage) but I will chip in what I can.

Thanks again !!!

—

**Comment by hippasus** [comment]
@surajravi I'm so glad that I can help. :)
