### ISSUE TITLE
Urgent: Exchange Rate Feed Down

### ISSUE THREAD

**Issue by ebkdev** [hippasus/ExchangeRates#13]
Over Quota
This application is temporarily over its serving quota.
http://rate-exchange.appspot.com/currency?from=USD&to=GBP

![image](https://f.cloud.github.com/assets/5868876/1481795/eaa9f33a-46d0-11e3-8437-001b93214cf4.png)

**Comment by hippasus** [comment]
Google rate API doesn't exist any more. I will find a replacement. You can get more details from issue #12 .
