### ISSUE TITLE
new issue with thw exchage converter

### ISSUE THREAD

**Issue by roee69** [hippasus/ExchangeRates#16]
Hi
I've been using you api for the last 4 months and it great but is stoped working at the last 4 days.
I saw that you started using the XE.com api can you please tell me why my code not working?

function forex() {
    var amount1 = document.getElementById("amount").value;
    $("#screen").html("You entered: " + amount1);
    var to = document.getElementById("to").value;
    var from = document.getElementById("from").value;
    var answer;
    var rate;
    $.getJSON("http://rate-exchange.appspot.com/currency?&callback=?", { from: from, to: to, q: amount1 }, function (response) {
        answer = response.v;
        rate = response.rate;

Thanks roee

**Comment by hippasus** [comment]
sorry, but what is the issue? any error message?

**Comment by roee69** [comment]
it has been fixed. i really dont know what was the problem but it works now.
thanks roee

**Comment by hippasus** [comment]
Oh... okay.
