### ISSUE TITLE
Reverted to float

### ISSUE THREAD

**Issue by GreatOldOne** [hippasus/ExchangeRates#19]
Good morning,

Why was my commit https://github.com/GreatOldOne/ExchangeRates/commit/434e97a0f35cadd2917b3d036ef7f60b57384f36 reverted?

Regards.

**Comment by GreatOldOne** [comment]
I've read the possible issue that caused you to revert it and addressed that with this comment:

https://github.com/hippasus/ExchangeRates/issues/17#issuecomment-33350122

Decimals SHOULD be quoted in JSON, you can google it yourself.

Another point is, the flaw is within his parser (which is unusual for a Haskell programmer to not examine the data he is receiving).

As I've already pointed with my pull request, floating points cannot represent decimals in binary, there will always be loss of precision.

> > > 3 \* 33.3
> > > 99.89999999999999

While it appears to be minimal, constantly performing arithmetic on it will eventually cause a significant loss of precision, which is unacceptable for financial operations.

Alas, if my pull request cannot be merged, I'll be forced to write my own parser directly from xe.com and will no longer be able to recommend this API for those who rely on precise calculations.

**Comment by GreatOldOne** [comment]
For reference, this is my Python class that accepts both a floating point rate (which is never stored as floating point but rather Decimal directly from the JSON str response) aswell as Decimal.
Web is my custom class for HTTP querying and parsing.

class RateExchange(Web):

```
"""Rate Exchange class."""

CURRENCIES = {
              "dollar": "USD",
              "euro": "EUR",
              "real": "BRL"
             }
EXCHANGE_API = "http://rate-exchange.appspot.com/currency"

def __init__(self, console):

    super(RateExchange, self).__init__()
    self.console = console
    self.rate = None

def setRate(self, fromCurrency, toCurrency):

    try:

        self.setURL("%s?from=%s&to=%s" % (RateExchange.EXCHANGE_API, fromCurrency, toCurrency))
        self.setContentType("application/json; charset=UTF-8")
        self.setUserAgent(self.console.config.userAgent)
        data = self.open(JSON=True, useDecimal=True)

        if data["from"] != fromCurrency or data["to"] != toCurrency:

            raise ExchangeError

        rate = Decimal(data["rate"])

        if rate <= 0:

            raise ExchangeError

    except (URLError, socketError, KeyError, InvalidOperation, ExchangeError):

        return "Failed to acquire current rate exchange."

    else:

        self.rate = rate

    return True

def toCurrency(self, value, currency=None):

    value = (Decimal(value) * self.rate)
    value = value.quantize(Decimal("0.01"), rounding=ROUND_HALF_EVEN)
    value = str(value).replace(".", ",", 1)

    if currency is not None:

        return "%s %s" % (value, currency)

    else:

        return value
```

**Comment by hippasus** [comment]
I don't think we should return string for the rate portion in the JSON result.

**Comment by GreatOldOne** [comment]
Well, as I've already mentioned several times, JSON doesn't have a definition for decimals. We either pass it as a string and let the client decide what to do with that data, an int representation (which is uglier), or a floating point.
Floating points will have the binary representation problem, as already mentioned.

Either way you decide. Do you want your API to be imprecise, which is a fairly important for financial operations?

Representations in JSON:

decimal:

"x.xxx", better approach. Simply let the client convert to his favorite data type.

int: 

rate = Decimal(string)
rate *= 100000000
rate = int(rate)

Sort of ugly compared to the first approach. Client must interpret the rate as an integer value and calculate to decimal from there.
In the example above decimal point should be based on a single-precision floating point.

float:

x.xxx, Loss of precision. Unacceptable for financial operations.

You can also add an extra field "from=USD&to=BRL&type=[int/float/decimal]" and always store that value in a Decimal object internally.
If you are fine with this method, let me now and I'll send a pull request.

Either way, I've already written my own xe.com parser with HTMLParser and I've not been using your API since then.

**Comment by GreatOldOne** [comment]
I'm closing this as the author doesn't seem to care.
Either way, I'm using my own parser by now and just wanted to help this project
