### ISSUE TITLE
Getting 500 Internal Server Error 

### ISSUE THREAD

**Issue by shankyTkoshy** [hippasus/ExchangeRates#2]
Getting 500 Internal Server Error on this URL (http://rate-exchange.appspot.com/currency?from=USD&to=EUR&q=1) . I am getting this error around 5:30 AM GMT 

Is this URL valid for specific timings ?

**Comment by hippasus** [comment]
@shankyTkoshy We've reached the [GAE URL Fetch Quota](https://developers.google.com/appengine/docs/quotas#UrlFetch) for the currency API.  Only 657,000 calls per day...

**Comment by shankyTkoshy** [comment]
Oh.. :( 

Thanks

**Comment by hippasus** [comment]
What do you think of caching Google's result for a while? The data may not be so real-time, but we can avoid exceeding this request quota.

**Comment by shankyTkoshy** [comment]
Yes i have stored data in mysql table but need to update with real time data.. Anyway thanks hippasus :)
