### ISSUE TITLE
Urgent Over Quota Issue

### ISSUE THREAD

**Issue by rashi3** [hippasus/ExchangeRates#21]
I am facing this problem from 2 days in morning at india time. I have implemented your api in my program and having this problem. Please confirm is this regular problem or do I need to do something on my side to solve this problem.

**Comment by adrian7** [comment]
I guess you'll be better fork-ing the repo and deploying your own app on Google App Engine.

**Comment by hippasus** [comment]
Yes, please deploy the app by your own if it means a lot to you.
