### ISSUE TITLE
Permanent response err: "failed to parse response from xe.com."

### ISSUE THREAD

**Issue by gekpp** [hippasus/ExchangeRates#24]
http://rate-exchange.appspot.com/currency?to=EUR&from=1&q=COL
{
err: "failed to parse response from xe.com."
}

The same on any currency

**Comment by adrian7** [comment]
The from parameter is wrong. You should have a valid currency code in there, and the q should be the "quantity" you are trying to convert.

**Comment by hippasus** [comment]
@adrian7 is right, thanks!
