### ISSUE TITLE
What is the the q parameter and what does v stand for in the response Json?

### ISSUE THREAD

**Issue by sabahang** [hippasus/ExchangeRates#25]
Sample request:
http://rate-exchange.appspot.com/currency?from=USD&to=USD&q=2

Sample Response:
{"to": "USD", "rate": 1.0, "from": "USD", "v": 2.0}

What are q and v ?

**Comment by hippasus** [comment]
USD to USD, why do you do that?

by checking this http://rate-exchange.appspot.com/currency?from=USD&to=EUR&q=2, you can easily find out that q stands for query amount,  and v for converted value.

```
{
    to: "EUR",
    rate: 0.7446,
    from: "USD",
    v: 1.4892
}
```

PS: q is an optional parameter.
