### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by ghost** [hippasus/ExchangeRates#33]
Hello,

Seems Google has changed the steps of apps deployment. Now all apps not working until they will be set up in proper way. You can find how to do it in Google developer panel.
![deployment](https://cloud.githubusercontent.com/assets/7500143/8845180/222efb6c-3125-11e5-8036-2b6ad10b38b7.PNG)

Regards

**Comment by hippasus** [comment]
please use http://2.rate-exchange-1.appspot.com/ instead.
